
<div class="row-fluid" id="cliente">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL; ?>equipamentos/novo"><button class="btn btn-success" id="">Adiconar Novo <i class="icon-plus icon-white"></i></button></a>
                    </div>
                </div>

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>

                            <th>Nome</th> 
                            <th>Modelo</th>
                            <th>Rack</th>
                            <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>  <th>Usuario</th> <?php endif; ?> 
                            <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>  <th></th> <?php endif; ?> 
                            <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>  <th></th> <?php endif; ?> 
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->equipamento) && !empty($this->equipamento)): ?>

                            <?php
                            foreach ($this->equipamento as $d):
                                ?>

                                <tr>
                                    <td><?php print $d->getNome(); ?></td>
                                    <td><?php print $d->getModelo(); ?></td>
                                    <td><?php print $d->getRacks()->getNome(); ?></td>

                                    <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>   <td><?php print $d->getUsuarios()->getNome(); ?></td>

                                    <?php endif; ?>
                                    <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>   <td><a rel="<?php print $d->getId(); ?>" href="<?php print URL . "equipamentos/editar/" . $d->getId(); ?>" id="delete"><i class=""><i class="icon-edit"></i></a></td>
                                    <?php endif; ?>
                                    <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>   <td><a rel="<?php print $d->getId(); ?>" href="<?php print URL . "coyonet_hpas/apagar/" . $d->getId(); ?>" id="delete"><i class=""><i class="icon-trash"></i></a></td>
                                    <?php endif; ?>
                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center alert-error">Não foi encontrado Dados</h2>
                <?php endif; ?>

            </div>
        </div>
    </div>
    <!-- /block -->
</div>

                <?php if (isset($this->paginacao) && !empty($this->paginacao) && (count($this->paginacao))) echo $this->paginacao; ?>

