<input type="text" value="" id="pesquisa" class="span4 m-wrap form-group pull-right span4 m-wrap" placeholder="Pesquisar"  />


<div class="row-fluid">
    <div class="block">
        <div class="pull-right">
            <div class="control-group custom-search-form centered">

            </div><!-- /input-group -->
        </div>
    </div>
</div>                    
<div class="row-fluid">

    <div class="block">

        <div class="block-content collapse in">
            <div class="span12">

                <div class="table-responsive">
                    <table  id="tabela" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">   
                        <thead>
                            <tr class="odd gradeA">
                                <th>Nº Cabo</th>
                                <th>Descrição</th>
                                <th>PPANEL</th>
                                <th>PP_PORT</th>
                                <th>Equipamento</th>
                                <th>Porta</th>
                                <th>Rack/Origem</th>
                                <th>Rack/Destino</th>
                                <th>Nº Cabo</th>
                                <th>Descrição</th>
                                <th>PPANEL</th>
                                <th>PP_PORT</th>
                                <th>Equipamento</th>
                                <th>Porta</th>
                            </tr>
                        </thead>

                        <tbody>
                            <?php if (isset($this->destino) && !empty($this->destino)): ?>

                                <?php
                                foreach ($this->destino as $d):
                                    ?>

                                    <tr>
                                        <td><?php print $d->getCabos()->getCodigo(); ?></td>
                                        <td><?php print $d->getCabos()->getDescricao(); ?></td>
                                        <td><?php print $d->getCabos()->getPatchpanel()->getNome(); ?></td>
                                        <td><?php print $d->getCabos()->getPatchpanelPorta(); ?></td>
                                        <td><?php print $d->getCabos()->getEquipamentos()->getNome(); ?></td>
                                        <td><?php print $d->getCabos()->getEquipamentosPorta(); ?></td>
                                        <td><?php print $d->getCabos()->getEquipamentos()->getRacks()->getNome(); ?></td>

                                        <td><?php print $d->getEquipamentos()->getRacks()->getNome(); ?></td>
                                        <td><?php print $d->getCodigo(); ?></td>
                                        <td><?php print $d->getDescricao(); ?></td>
                                        <td><?php print $d->getPatchpanel()->getNome(); ?></td>
                                        <td><?php print $d->getPatchpanelPorta(); ?></td>
                                        <td><?php print $d->getEquipamentos()->getNome(); ?></td>
                                        <td><?php print $d->getEquipamentosPorta(); ?></td>





                                    </tr>
                                <?php endforeach; ?>

                            </tbody>
                        </table>

                    <?php else: ?>
                        <h2 class="text-center alert-error">Não foi encontrado Dados</h2>
                    <?php endif; ?>
                </div>

            </div>
        </div>
    </div>
</div> 
