<!--
<div class="row-fluid">



     block 
    <div class="block">

        <div class="block-content collapse in">
            <div class="span12">

                
                    <div class="pull-right">
                        <form role="form" class="form-horizontal" method="post" action="">
                            <div class="form-group">
                                <label class="col-xs-10 col-sm-2 col-md-1 control-label" for="v_search">Pesquisa:</label>
                                <div class="controls">
                                    <input type="text" placeholder="codigo(cabo)" value="" name="v_search" id="v_search" class="span6 m-wrap">
                                </div>
                                <div class="form-group">
                                    <label class="col-xs-10 col-sm-2 col-md-1 control-label" for="filters">Filtros:</label>
                                    <div class="controls">
                                        <select class="form-control" name="section_id">
                                            <option value="">Cabo</option>
                                            <option value="all">Equipamento</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <button class="btn btn-primary" value="search" name="search" type="submit">Search</button>
                                    <button class="btn btn-default" value="reset" name="reset" type="reset">Reset</button>
                                </div>
                            </div>

                        </form>
                    </div>

                    <div class="table-responsive"> 
                    <table   class="table table-striped table-bordered table-hover" cellspacing="0" width="100%" id="tabela" >   
                        <thead>
                            <tr>
                                <th>NºCabo</th>
                                <th>PPANEL</th>
                                <th>PPORT</th>
                                <th>Equip</th>
                                <th>Port</th>
                                <th>Rack/Origem</th>

                                <th>Rack/Destino</th>
                                <th>NºCabo</th>
                                <th>PPANEL</th>
                                <th>PPORT</th>
                                <th>Equip</th>
                                <th>Port</th>
                            </tr>
                        </thead>

                        <tbody>
                            <?php if (!isset($this->rack) && empty($this->rack)): ?>

                                <?php
                                // foreach ($this->rack as $d):
                                ?>

                                <tr>
                                    <td><?php print "aaaa23errr"; ?></td>
                                    <td><?php print "aaaa343344"; ?></td>
                                    <td><?php print "aaaab3444"; ?></td>
                                    <td><?php print "aaaa76543333"; ?></td>
                                    <td><?php print "aaaa87653333"; ?></td>
                                    <td><?php print "aaaahgfc444444445"; ?></td>
                                    <td><?php print "aaaa344f333333"; ?></td>
                                    <td><?php print "aaaa765f44444"; ?></td>
                                    <td><?php print "aaaa432f333333f"; ?></td>
                                    <td><?php print "aaaa8765g222222"; ?></td>
                                    <td><?php print "aaaa8765g3333333"; ?></td>
                                    <td><?php print "aaaa8765g44444444"; ?></td>
                                    
                                    
                                </tr>


                            </tbody>
                        </table>
                    <?php else: ?>
                        <h3 class="text-center alert">Não foi encontrado Dados</h3>
                    <?php endif; ?>


                </div>
            </div>
        </div>
         /block 
    </div>
</div>



-->
