
<div class="span10 " id="content" style="margin-left: 300px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right">Dados do Alarme</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form  id="alarme" class="form-horizontal" method="POST">
                        <fieldset>
                            <div class="control-group">
                                <label class="control-label">criated<span class="required" >*</span></label>
                                <div class="controls">
                                    <input type="text" name="criated" data-required="1" class="span6 m-wrap" value="<?php if (isset($this->dados)) print $this->dados->getCriated(); ?>"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">severity<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="severity" type="text" class="span6 m-wrap" value="<?php if (isset($this->dados)) print $this->dados->getSeverity(); ?>"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">device service<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="device_service" type="text" class="span6 m-wrap" value="<?php if (isset($this->dados)) print $this->dados->getDeviceService(); ?>"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">details<span class="required">*</span></label>
                                <div class="controls">
                                    <textarea name="details" id="descricao" class="span6 m-wrap" rows="5" cols="30" ><?php if (isset($this->dados)) print $this->dados->getDetails(); ?></textarea>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">data<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="date" name="data" />    
                                </div>
                            </div>


                            <input name="enviar" type="hidden" value="1"/>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary" id="novo">Salvar Dados</button>
                                <button type="reset" class="btn">Cancelar</button>
                            </div>
                        </fieldset>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>
</div>