
<div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL; ?>cabos/novo"><button class="btn btn-success" id="">Adiconar Novo <i class="icon-plus icon-white"></i></button></a>
                    </div>
                </div>

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr class="text-success">
                            <th>Nº Cabo</th>
                            <th>Descrição</th>
                            <th>PPANEL</th>
                            <th>PP_PORT</th>
                            <th>Equipamento</th>
                            <th>Porta</th>
                            <th>Rack/Origem</th>

                            <th>Rack/Destino</th>
                            <th>Nº Cabo</th>
                            <th>Descrição</th>
                            <th>PPANEL</th>
                            <th>PP_PORT</th>
                            <th>Equipamento</th>
                            <th>Porta</th>
                            <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>  <th>Usuario</th> <?php endif; ?> 
                            <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>  <th></th> <?php endif; ?> 
                            <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>  <th></th> <?php endif; ?> 
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->destino) && !empty($this->destino)): ?>

                            <?php
                            foreach ($this->destino as $d):
                                ?>

                        <tr class="text-info">
                                    <td><?php print $d->getCabos()->getCodigo(); ?></td>
                                    <td><?php print $d->getCabos()->getDescricao(); ?></td>
                                    <td><?php print $d->getCabos()->getPatchpanel()->getNome(); ?></td>
                                    <td><?php print $d->getCabos()->getPatchpanelPorta(); ?></td>
                                    <td><?php print $d->getCabos()->getEquipamentos()->getNome(); ?></td>
                                    <td><?php print $d->getCabos()->getEquipamentosPorta(); ?></td>
                                    <td><?php print $d->getCabos()->getEquipamentos()->getRacks()->getNome(); ?></td>

                                    <td><?php print $d->getEquipamentos()->getRacks()->getNome(); ?></td>
                                    <td><?php print $d->getCodigo(); ?></td>
                                    <td><?php print $d->getDescricao(); ?></td>
                                    <td><?php print $d->getPatchpanel()->getNome(); ?></td>
                                    <td><?php print $d->getPatchpanelPorta(); ?></td>
                                    <td><?php print $d->getEquipamentos()->getNome(); ?></td>
                                    <td><?php print $d->getEquipamentosPorta(); ?></td>
                                    <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>   <td><?php print $d->getUsuarios()->getNome(); ?></td>
                                    <?php endif; ?>
                                    <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>   <td><a rel="<?php print $d->getId(); ?>" href="<?php print URL . "equipamentos/editar/" . $d->getId(); ?>" id="delete"><i class="icon-edit"></i></a></td>
                                    <?php endif; ?>
                                    <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>   <td><a rel="<?php print $d->getId(); ?>" href="<?php print URL . "coyonet_hpas/apagar/" . $d->getId(); ?>" id="delete"><i class="icon-trash"></i></a></td>
                                    <?php endif; ?>
                                    <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>   <td><a rel="<?php print $d->getId(); ?>" href="<?php print URL . "/impressao/impressao"  ?>" id="delete"><i class="icon-print"</i></a></td>
                                    <?php endif; ?>
                                    
                                    
                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center alert-error">Não foi encontrado Dados</h2>
                <?php endif; ?>

                <?php if (isset($this->paginacao) && !empty($this->paginacao) && (count($this->paginacao))) echo $this->paginacao; ?>

            </div>
        </div>
    </div>
    <!-- /block -->
</div>