
        <input type="text" value="" id="pesquisa" class="span4 m-wrap form-group pull-right span4 m-wrap" placeholder="Pesquisar"  />

<div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group pull-right">
                        <a href="<?php print URL; ?>cabos/novo"><button class="btn btn-success" id="">Adiconar Novo <i class="icon-plus icon-white"></i></button></a>
                    </div>
                </div>
                <div class="table-responsive">
                    <table  id="tabela" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">  
                        <thead>

                        <th>Nº Cabo</th>

                        <th>Descrição</th>
                        <th>Equipamento</th>
                        <th>Porta</th>
                        <th>Rack</th>
                        </thead>

                        <tbody>
                            <?php if (isset($this->destino) && !empty($this->destino)): ?>

                                <?php
                                foreach ($this->destino as $d):
                                    ?>

                                    <tr>
                                        <td><?php print $d->getCodigo(); ?></td>
                                        <td><?php print $d->getDescricao(); ?></td>
                                        <td><?php print $d->getEquipamentos()->getNome(); ?></td>
                                        <td><?php print $d->getEquipamentosPorta(); ?></td>
                                        <td><?php print $d->getEquipamentos()->getRacks()->getNome(); ?></td>
                                    </tr>
                                <?php endforeach; ?>

                                <?php foreach ($this->cabo as $t):
                                    ?>

                                    <tr>
                                        <td><?php print $t->getCodigo(); ?></td>
                                        <td><?php print $t->getDescricao(); ?></td>
                                        <td><?php print $t->getEquipamentos()->getNome(); ?></td>
                                        <td><?php print $t->getEquipamentosPorta(); ?></td>
                                        <td><?php print $t->getEquipamentos()->getRacks()->getNome(); ?></td>
                                    </tr>
                                <?php endforeach; ?>  

                            </tbody>
                        </table>
                    <?php else: ?>
                        <h2 class="text-center alert-error">Não foi encontrado Dados</h2>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>