

<table  class="table table-striped table-bordered">   
    <thead>
        <tr>

            <th>criated</th> 
            <th>severity</th>
            <th>device_service</th>

        </tr>
    </thead>

    <tbody>
      
        <?php if (isset($this->dados) && !empty($this->dados)): ?>

            <tr>
                <td><?php print $this->dados['criated']; ?></td>
                <td><?php print $this->dados['severity']; ?></td>
                <td><?php print $this->dados['device_service']; ?></td>

            </tr>

        <?php endif; ?>

    </tbody>
</table>

<div class="span10 " id="content" style="margin-left: 300px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right">Descricao</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <p><?php print $this->dados['details']; ?></p>


                </div>
            </div>
        </div>
    </div>
</div>



