
<div class="span10 " id="content" style="margin-left: 300px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right">Dados  Radios</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form   class="form-horizontal" method="POST">
                        <fieldset>
                            <div class="control-group">
                                <label class="control-label">Canal<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="text" name="canal" data-required="1" class="span6 m-wrap" value="<?php if (isset($this->dados)) print $this->dados->getCanal(); ?>"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Status<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="status" type="text" class="span6 m-wrap" value="<?php if (isset($this->dados)) print $this->dados->getStatus(); ?>"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Observação<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="obs" type="text" class="span6 m-wrap" value="<?php if (isset($this->dados)) print $this->dados->getObs(); ?>"/>
                                </div>
                            </div>
                            <input name="enviar" type="hidden" value="1"/>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary" id="novo">Salvar Dados</button>
                                <button type="reset" class="btn">Cancelar</button>
                            </div>
                        </fieldset>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>
