<div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL . $this->link; ?>"><button class="btn btn-success">Novo Usuario <i class="icon-plus icon-white"></i></button></a>
                    </div>
                </div>
                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>
                            <th>Nome</th> 
                            <th>Login</th>
                            <th>Nivel</th>
                            <th>Alterar</th>
                            <th>Apagar</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->usuarios) && !empty($this->usuarios)): ?>
                            <?php foreach ($this->usuarios as $dados): ?>

                                <tr>
                                    <td><?php print $dados->getNome(); ?></td>
                                    <td><?php print $dados->getLogin(); ?></td>
                                    <td><?php print $dados->getNivel(); ?></td>
                                    <td><a rel="<?php print $dados->getId(); ?>" href="<?php print URL . "usuario/editar/" . $dados->getId(); ?>" id="altera"><i class="">Alterar</i></a></td>
                                    <td><a rel="<?php print $dados->getId(); ?>" href="<?php print URL . "usuario/apagar/" . $dados->getId(); ?>" id="delete"><i class="">Apagar</i></a></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center text-error">Nenhum usuario cadastrado</h2>
                <?php endif; ?>
                <?php if (isset($this->paginacao) && !empty($this->paginacao)) echo $this->paginacao; ?>
            </div>
        </div>
    </div>
    <!-- /block -->
</div>